### ISSUE TITLE
return all errors and results instead of cancel all transactions

### ISSUE THREAD

**Issue by keremcankabadayi** [Trendyol/go-future#2]
assuming i need to index documents to CB and publish success transactions to topic. If any error occurs, whole process is cancelled and return the error. 

```
	// Wait for all. If any error occurred, don't wait and return first error.
	for i := 0; i < len(futures); i++ {
		ft := <-ch
		if ft.Err != nil {
			return ft.Err
		}
	}
```

proposal: lets not cancel whole process and collect errors from routines. so, we can handle errors and results seperately.

**Comment by hamzagoc** [comment]
We have a function that waits for all futures, even if one of them gets an error. You can use future.WaitAllSilently.

- Maybe, We can write a version of WaitAllSilently that returns an error list.
- Additionally, if WaitAllSilently is not a clear name, we can change the name of this function.

For example, the use of future.WaitAllSilently and collect errors

```go

func Test_Future_WaitAllSilently(t *testing.T) {
	// Given
	futures := []*future.Future[string]{
		future.Run[string](fn),
		future.Run[string](fnWithError),
		future.Run[string](fnWithError),
		future.Run[string](fn),
		future.Run[string](fnWithError),
	}
	// When
	future.WaitAllSilently(futures)

	// Then
	errors := make([]error, 0)
	for i := range futures {
		if futures[i].Err != nil {
			errors = append(errors, futures[i].Err)
		}
	}

	assert.Equal(t, len(errors), 3)
}

func fn() (string, error) {
	waitMillis := rand.Intn(100)
	time.Sleep(time.Duration(waitMillis) * time.Millisecond)
	return "expectedVal", nil
}
func fnWithError() (string, error) {
	waitMillis := rand.Intn(100)
	time.Sleep(time.Duration(waitMillis) * time.Millisecond)
	return "", errors.New("error occurred")
}

```

**Comment by hamzagoc** [comment]
I added new function WaitAllContinueOnError.

> WaitAllContinueOnError function waits for the completion of specified Futures and continues even if an error occurs during the process. It returns a list of errors that occurred.

```go
func Test_Future_WaitAllContinueOnError(t *testing.T) {
	// Given
	futures := []*future.Future[string]{
		future.Run[string](fn),
		future.Run[string](fnWithError),
		future.Run[string](fnWithError),
		future.Run[string](fn),
		future.Run[string](fnWithError),
	}
	// When
	errors := future.WaitAllContinueOnError(futures)

	// Then
	assert.Equal(t, len(errors), 3)
}
```
